### ISSUE TITLE
Paper Mario TTYD - Black screen in rogueport sewers on RDNA3

### ISSUE THREAD

**Issue by coinkillerl** [sudachi-emu/sudachi#121]
In the Paper Mario The Thousand Year Door remake, entering the rogueport sewers will render a black screen. UI is still rendered, audio still works and the game still runs.

GPU : RX 7800XT, latest mesa drivers
OS : CachyOS Linux (Arch-based)

[sudachi_log.txt](https://github.com/sudachi-emu/sudachi/files/15407139/sudachi_log.txt)
This issue is said to happen in non-RDNA3 amd cards as well, but i can't confirm personally.

**Comment by jarrodnorwell** [comment]
I'll need to install my RX 580 to begin working on this issue, it may be a day or two as I'm currently waiting for an app to be approved for the App Store

**Comment by AngeryCinnabon** [comment]
Will this be fixable on android too? or is that out of scope?

**Comment by carr654** [comment]
Yes please for fix. Ryujinx has the fix but I like the hone menu for the switch

**Comment by carr654** [comment]
> [Ryujinx/Ryujinx@e65effc](https://github.com/Ryujinx/Ryujinx/commit/e65effcb05c40247fb717b3c2409abce7ffa10fc) he needs to port this over.

Once u implement this can u add this I  too otherwise save boxes are black and so are the coins https://github.com/Ryujinx/Ryujinx/pull/6853

**Comment by jarrodnorwell** [comment]
Should be fixed in the latest release, please feel free to test and let me know so this can be closed

**Comment by coinkillerl** [comment]
> Should be fixed in the latest release, please feel free to test and let me know so this can be closed

Seems to be fixed on my end.

**Comment by carr654** [comment]
> Should be fixed in the latest release, please feel free to test and let me know so this can be closed

Amazing thank you, I'm currently out at the moment but will give it a go when I get back

**Comment by jarrodnorwell** [comment]
> > Should be fixed in the latest release, please feel free to test and let me know so this can be closed
> 
> 
> 
> Amazing thank you, I'm currently out at the moment but will give it a go when I get back 

No worries! I'll keep checking in to see if there's any new comments

**Comment by Hicham-Bensaid** [comment]
Hello.
Still having the problem on android (Samsung s24+ exynos 2400 xclipse): black screen on sewers followed by a crash while blindly moving.

**Comment by carr654** [comment]
> > > Should be fixed in the latest release, please feel free to test and let me know so this can be closed
> > 
> > 
> > Amazing thank you, I'm currently out at the moment but will give it a go when I get back
> 
> No worries! I'll keep checking in to see if there's any new comments

Works great for me on legion go, thank you :) 

Uploading VID_20240525_220442.mp4…
